# Generated by Django 3.1.5 on 2021-02-08 09:38

import django.contrib.postgres.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('date_of_birth', models.DateField()),
                ('about', models.TextField()),
                ('auth_provider', models.CharField(default='email', max_length=300)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('host_reviews', django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), null=True, size=None)),
                ('host_rating', models.FloatField(default=0)),
                ('interests', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), null=True, size=None)),
                ('events_attended', django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), null=True, size=None)),
                ('events_hosted', django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), null=True, size=None)),
                ('password', models.CharField(max_length=50)),
                ('social_accounts', models.JSONField(null=True)),
                ('first_timer', models.BooleanField(default=True)),
                ('account_blocked', models.BooleanField(default=False)),
                ('deactivated_account', models.BooleanField(default=False)),
                ('profile_picture', models.URLField()),
                ('event_highlights', django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), null=True, size=None)),
                ('following', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), null=True, size=None)),
                ('followers', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), null=True, size=None)),
                ('notification', django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), null=True, size=None)),
                ('user_logs', django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), null=True, size=None)),
                ('calender', django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), null=True, size=None)),
                ('analytics', models.JSONField(null=True)),
                ('date_joined', models.DateField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
